#!/usr/bin/env python3

import random

def main():

    wordbank= ["indentation", "spaces"]

    tlgstudents= ['Albert', 'Anthony', 'Brenden', 'Craig', 'Deja', 'Elihu', 'Eric', 'Giovanni', 'James', 'Joshua', 'Maria', 'Mohamed', 'PJ', 'Philip', 'Sagan', 'Suchit', 'Meka', 'Trey', 'Winton', 'Xiuxiang', 'Yaping']

    wordbank.append(4)

    choice= int(input("Pick a number between 0 and 20 \n>"))
    student_name= tlgstudents[choice]

    print(random.choice(tlgstudents) + " always uses " + str(wordbank[2]) + " " + wordbank[1] + " to indent")
 

main()
